### ISSUE TITLE
Reverse dependencies may need CXX_STD set to C++11 or C++14

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#356]
When reverse-dependency checking the release candidate for 0.10.7.4.0 (with the upstream maintenance release 10.7.4) we noticed three packages failing over having a `data` object which, as @conradsnicta reminded us, conflicts with `std::data()` in C++17 (if and when `using namespace std;` is used) as `g++` version 11 now defaults to C++17.  

This affects packages
- [x] RcppSMC : filed [issue #68](https://github.com/rcppsmc/rcppsmc/issues/68) on 2021-11-24; fixed in [PR #69](https://github.com/rcppsmc/rcppsmc/pull/69)
- [x] RSSL: filed [PR #14](https://github.com/jkrijthe/RSSL/pull/14) on 2021-11-25, merged 2021-11-26
- [x] sbfc: files [PR #1](https://github.com/vkrakovna/sbfc/pull/1) on 2021-11-25, merged 2021-11-25

and I plan to contact the maintainers (myself for RcppSMC) to suggest adding `CXX_STD=CXX11` (or `CXX14`) which addresses the issue in question, and keep tabs here on whether these have been updated.

**Comment by eddelbuettel** [comment]
Now (already !!) fixed in source, I may leave it open til all three are updated at CRAN...

**Comment by eddelbuettel** [comment]
This issue has by now been taken care of at the CRAN level with an email to affected maintainers, including those for `RSSL` and `sbfc` (and `RcppSMC` has already been fixed at CRAN as well). As it is monitored there this ticket can be closed.
